language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test -u
deploy:
  provider: pages
  skip_cleanup: false
  github_token: $github_token
  local_dir: build
  on:
    branch: master